# create github actions to deploy vue app to amazon S3
name: Deployment

on:
  push:
    branches:
      - develop
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Map branch to environment
        id: map_branch_to_env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "::set-output name=environment::development"
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "::set-output name=environment::staging"
          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            echo "::set-output name=environment::production"
          else
            echo "::set-output name=environment::unknown"
          fi

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.11.0"

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          env_file: env/${{ steps.map_branch_to_env.environment }}.env
        run: npm run build-only

      - name: Deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "dist"
